const project = [

    // Liste des MOC Marvel //
    {//Agatha on the Witches' road//
        id: "moc-marvel-1",
        name: {
            fr: "Agatha sur la route des sorcières",
            en: "Agatha on the Witches' road",
        },
        href: "../Portfolio/Marvel/Witches-road.html",
        key: "project_Agatha_on_the_Witches_road",
        date: "2024-10-09",
        relevance: 3,
        filter: "Agatha: All along",
        img: "../img/Miniatures/Witches road.jpg",
        alt: "Agatha on the Witches' road",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Taweret's Boat//
        id: "moc-marvel-2",
        name: {
            fr: "Le bateau de Taweret",
            en: "Taweret's Boat",
        },
        href: "../Portfolio/Marvel/Taweret's-boat.html",
        key: "project_Taweret_Boat",
        date: "2024-10-08",
        relevance: 3,
        filter: "Moon Knight",
        img: "../img/Miniatures/taweret's boat.jpg",
        alt: "Taweret's Boat",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Endgame final battle//
        id: "moc-marvel-3",
        name: {
            fr: "Bataille finale endgame",
            en: "Endgame final battle",
        },
        href: "../Portfolio/Marvel/Endgame-final-battle.html",
        key: "project_Endgame_final_battle",
        date: "2024-08-09",
        relevance: 3,
        filter: "Avengers : Endgame",
        img: "../img/Miniatures/Endgame final battle.jpg",
        alt: "Endgame final battle",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Thor VS Surtur//
        name: {
            fr: "Thor VS Surtur",
            en: "Thor VS Sutur",
        },
        id: "moc-marvel-4",
        href: "../Portfolio/Marvel/Thor-escapes-from-Muspelheim.html",
        key: "project_Thor_VS_Surtur",
        date: "2024-08-09",
        relevance: 3,
        filter: "Thor : Ragnarok",
        img: "../img/Miniatures/thor escapes.jpg",
        alt: "Thor VS Surtur",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Steve Rogers transformation scene//
        id: "moc-marvel-5",
        name: {
            fr: "Transformation de Steve Rogers",
            en: "Steve Rogers transformation scene",
        },
        href: "../Portfolio/Marvel/Steve-Rogers-transformation.html",
        key: "project_Steve_Rogers_transformation_scene",
        date: "2024-08-07",
        relevance: 3,
        filter: "Captain America : First Avenger",
        img: "../img/Miniatures/Steve Rogers transformation scene.jpg",
        alt: "Steve Rogers transformation scene",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Loki & Mobius in Pompeii//
        id: "moc-marvel-6",
        name: {
            fr: "Loki & Mobius à Pompéi",
            en: "Loki & Mobius in Pompeii",
        },
        href: "../Portfolio/Marvel/Pompeii.html",
        key: "project_Loki_Mobius_in_Pompeii",
        date: "2024-08-04",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/pompeii.jpg",
        alt: "Loki & Mobius in Pompeii",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Black Widow death scene//
        id: "moc-marvel-7",
        name: {
            fr: "Mort de Black Widow",
            en: "Black Widow death scene",
        },
        href: "../Portfolio/Marvel/Black-Widow-Death-Scene.html",
        key: "project_Black_Widow_death_scene",
        date: "2024-08-02",
        relevance: 3,
        filter: "Avengers : Endgame",
        img: "../img/Miniatures/Black widow death scene.jpg",
        alt: "Black Widow death scene",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Deadpool 3 opening scene//
        id: "moc-marvel-8",
        name: {
            fr: "Scène d'intro de Deadpool 3",
            en: "Deadpool 3 opening scene",
        },
        href: "../Portfolio/Marvel/Deadpool-and-Wolverine-opening-scene.html",
        key: "project_Deadpool_3_opening_scene",
        date: "2024-07-31",
        relevance: 3,
        filter: "Deadpool & Wolverine",
        img: "../img/Miniatures/deadpool.jpg",
        alt: "Deadpool 3 opening scene",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Iron man 2 boxing ring//
        id: "moc-marvel-9",
        name: {
            fr: "Ring de boxe de Iron man 2",
            en: "Iron man 2 boxing ring",
        },
        href: "../Portfolio/Marvel/Natalie-Rushman.html",
        key: "project_Iron_man_2_boxing_ring",
        date: "2023-12-31",
        relevance: 3,
        filter: "Iron man 2",
        img: "../img/Miniatures/Natalie Rushman.jpg",
        alt: "Iron man 2 boxing ring",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Hulk VS Leviathan//
        id: "moc-marvel-10",
        name: {
            fr: "Hulk VS Leviathan",
            en: "Hulk VS Leviathan",
        },
        href: "../Portfolio/Marvel/Hulk-VS-Leviathan.html",
        key: "project_Hulk_VS_Leviathan",
        date: "2023-12-31",
        relevance: 3,
        filter: "Avengers",
        img: "../img/Miniatures/hulk.jpg",
        alt: "Hulk VS Leviathan",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Loki, God of stories//
        id: "moc-marvel-11",
        name: {
            fr: "Loki, Dieu des histoires",
            en: "Loki, God of stories",
        },
        href: "../Portfolio/Marvel/Loki-God-of-Stories.html",
        key: "project_Loki_God_of_stories",
        date: "2023-12-30",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/god of stories.jpg",
        alt: "Loki, God of stories",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Shuri meets Killmonger//
        id: "moc-marvel-12",
        name: {
            fr: "Shuri rencontre Killmonger",
            en: "Shuri meets Killmonger",
        },
        href: "../Portfolio/Marvel/Wakanda-throne.html",
        key: "project_Shuri_meets_Killmonger",
        date: "2023-12-30",
        relevance: 3,
        filter: "Black Panther : Wakanda Forever",
        img: "../img/Miniatures/wakanda throne.jpg",
        alt: "Shuri meets Killmonger",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Tomb of Alexander the Great//
        id: "moc-marvel-13",
        name: {
            fr: "La tombe d'Alexandre le Grand",
            en: "Tomb of Alexander the Great",
        },
        href: "../Portfolio/Marvel/Moon-Knight-discovers-a-Tomb.html",
        key: "project_Tomb_of_Alexander_the_Great",
        date: "2023-12-30",
        relevance: 3,
        filter: "Moon Knight",
        img: "../img/Miniatures/moon knight (2).jpg",
        alt: "Tomb of Alexander the Great",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Loki meets Victor Timely (2)//
        id: "moc-marvel-14",
        name: {
            fr: "Loki rencontre Victor Timely",
            en: "Loki meets Victor Timely",
        },
        href: "../Portfolio/Marvel/Victor-timely-2.html",
        key: "project_Loki_meets_Victor_Timely_2",
        date: "2023-11-15",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/timely (2).jpg",
        alt: "Loki meets Victor Timely (2)",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Ouroboros meets Loki//
        id: "moc-marvel-15",
        name: {
            fr: "Ouroboros rencotnre Loki",
            en: "Ouroboros meets Loki",
        },
        href: "../Portfolio/Marvel/Ouroborus.html",
        key: "project_Ouroboros_meets_Loki",
        date: "2023-11-04",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/Ouroboros.jpg",
        alt: "Ouroboros meets Loki",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Citadel of He Who Remains//
        id: "moc-marvel-16",
        name: {
            fr: "Citadelle de Celui qui Demeure",
            en: "Citadel of He Who Remains",
        },
        href: "../Portfolio/Marvel/He-Who-Remains.html",
        key: "project_Citadel_of_He_Who_Remains",
        date: "2023-11-02",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/He who remains.jpg",
        alt: "Citadel of He Who Remains",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//GOTG3 Final fight//
        id: "moc-marvel-17",
        name: {
            fr: "Bataille finale des Guardiens 3",
            en: "GOTG3 Final fight",
        },
        href: "../Portfolio/Marvel/GOTG3-final-battle-scene.html",
        key: "project_GOTG3_Final_fight",
        date: "2023-07-07",
        relevance: 3,
        filter: "Guardians of the Galaxy vol.3",
        img: "../img/Miniatures/GOTG3.jpg",
        alt: "GOTG3 Final fight",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Copying human identities//
        id: "moc-marvel-18",
        name: {
            fr: "Copier l'identité des humains",
            en: "Copying human identifies",
        },
        href: "../Portfolio/Marvel/Secret-Invasion.html",
        key: "project_Copying_human_identities",
        date: "2023-07-06",
        relevance: 3,
        filter: "Secret Invasion",
        img: "../img/Miniatures/secret invasion.jpg",
        alt: "Copying human identities",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Loki meets Victor Timely (1)//
        id: "moc-marvel-19",
        name: {
            fr: "Loki rencontre Victor Timely (1)",
            en: "Loki meets Victor Timely (1)",
        },
        href: "../Portfolio/Marvel/Victor-timely-1.html",
        key: "project_Loki_meets_Victor_Timely_1",
        date: "2023-03-19",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/timely (1).jpg",
        alt: "Loki meets Victor Timely (1)",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Sanctum Sanctorum//
        id: "moc-marvel-20",
        name: {
            fr: "Saints des Saints",
            en: "Sanctum Sanctorum",
        },
        href: "../Portfolio/Marvel/Sanctum-sanctorum-1.html",
        key: "project_Sanctum_Sanctorum",
        date: "2023-03-19",
        relevance: 3,
        filter: "Doctor Strange",
        img: "../img/Miniatures/Stairs.jpg",
        alt: "Sanctum Sanctorum",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Shang-chi VS Wenwu//
        id: "moc-marvel-21",
        name: {
            fr: "Shang-chi VS Wenwu",
            en: "Shang-chi VS Wenwu",
        },
        href: "../Portfolio/Marvel/Shang-chi.html",
        key: "project_Shang_chi_VS_Wenwu",
        date: "2023-02-12",
        relevance: 3,
        filter: "Shang-chi",
        img: "../img/Miniatures/shangchi.jpg",
        alt: "Shang-chi VS Wenwu",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Iron heart reveal//
        id: "moc-marvel-22",
        name: {
            fr: "1ère apparition de Iron Heart",
            en: "Iron Heart reveal",
        },
        href: "../Portfolio/Marvel/Iron-Heart.html",
        key: "project_Iron_heart_reveal",
        date: "2022-12-30",
        relevance: 3,
        filter: "Iron Heart",
        img: "../img/Miniatures/iron heart.jpg",
        alt: "Iron heart reveal",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Tony in the snow//
        id: "moc-marvel-23",
        name: {
            fr: "Tony dans la neige",
            en: "Tony in the snow",
        },
        href: "../Portfolio/Marvel/Iron-man-3.html",
        key: "project_Tony_in_the_snow",
        date: "2022-08-10",
        relevance: 3,
        filter: "Iron man 3",
        img: "../img/Miniatures/snow.jpg",
        alt: "Tony in the snow",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Doctor strange meets Mordo//
        id: "moc-marvel-24",
        name: {
            fr: "Doctor Strange rencontre Mordo",
            en: "Doctor Strange meets Mordo",
        },
        href: "../Portfolio/Marvel/Shamballa.html",
        key: "project_Doctor_strange_meets_Mordo",
        date: "2022-08-08",
        relevance: 3,
        filter: "Doctor Strange",
        img: "../img/Miniatures/doctorstrange.jpg",
        alt: "Doctor strange meets Mordo",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Steve 1st fight//
        id: "moc-marvel-25",
        name: {
            fr: "1er combat de Steve",
            en: "Steve 1st fight",
        },
        href: "../Portfolio/Marvel/Captain-America-first-fight.html",
        key: "project_Steve_1st_fight",
        date: "2022-08-08",
        relevance: 3,
        filter: "Captain America : First Avenger",
        img: "../img/Miniatures/steve.jpg",
        alt: "Steve 1st fight",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Tony discovers time travel//
        id: "moc-marvel-26",
        name: {
            fr: "Tony découvre le voyage dans le temps",
            en: "Tony discovers time travel",
        },
        href: "../Portfolio/Marvel/Time-Travel.html",
        key: "project_Tony_discovers_time_travel",
        date: "2022-08-07",
        relevance: 3,
        filter: "Avengers : Endgame",
        img: "../img/Miniatures/timetravel.jpg",
        alt: "Tony discovers time travel",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Morgan Stark//
        id: "moc-marvel-27",
        name: {
            fr: "Morgan Stark",
            en: "Morgan Stark",
        },
        href: "../Portfolio/Marvel/Morgan-Stark.html",
        key: "project_Morgan_Stark",
        date: "2022-08-07",
        relevance: 3,
        filter: "Avengers : Endgame",
        img: "../img/Miniatures/morgan.jpg",
        alt: "Morgan Stark",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Red Richards turn into spaghetti//
        id: "moc-marvel-28",
        name: {
            fr: "Red Richards transformé en spaghetti",
            en: "Red Richards turn into spaghetti",
        },
        href: "../Portfolio/Marvel/Red-Richards-turn-into-spaghetti.html",
        key: "project_Red_Richards_turn_into_spaghetti",
        date: "2022-07-10",
        relevance: 3,
        filter: "Doctor Strange in the multiverse of madness",
        img: "../img/Miniatures/spaghettis.jpg",
        alt: "Red Richards turn into spaghetti",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//The Illuminati//
        id: "moc-marvel-29",
        name: {
            fr: "Les Illuminati",
            en: "The Illuminati",
        },
        href: "../Portfolio/Marvel/Illuminati.html",
        key: "project_The_Illuminati",
        date: "2022-07-10",
        relevance: 3,
        filter: "Doctor Strange in the multiverse of madness",
        img: "../img/Miniatures/illuminati.jpg",
        alt: "The Illuminati",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Thor with Guardians//
        id: "moc-marvel-30",
        name: {
            fr: "Thor avec les Gardiens",
            en: "Thor with Guardians",
        },
        href: "../Portfolio/Marvel/Thor-with-GOTG.html",
        key: "project_Thor_with_GOTG",
        date: "2022-07-10",
        relevance: 3,
        filter: "Thor : Love and Thunder",
        img: "../img/Miniatures/thor with GOTG.jpg",
        alt: "Thor with Guardians",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Strange at mount Everest//
        id: "moc-marvel-31",
        name: {
            fr: "Strange au mont Everest",
            en: "Strange at mount Everest",
        },
        href: "../Portfolio/Marvel/Doctor-Strange-on-Everest.html",
        key: "project_Strange_at_mount_Everest",
        date: "2022-06-05",
        relevance: 3,
        filter: "Doctor Strange",
        img: "../img/Miniatures/everest.jpg",
        alt: "Strange at mount Everest",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Spiderman My back ! scene//
        id: "moc-marvel-32",
        name: {
            fr: "Scène 'Mon dos !' de Spiderman",
            en: "Spiderman 'My back !' scene",
        },
        href: "../Portfolio/Marvel/My-back-Spiderman-3.html",
        key: "project_Spiderman_My_back_scene",
        date: "2022-06-05",
        relevance: 3,
        filter: "Spiderman : No way home",
        img: "../img/Miniatures/my back.jpg",
        alt: "Spiderman My back ! scene",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Tony build Mark I//
        id: "moc-marvel-33",
        name: {
            fr: "Tony construit la Mark I",
            en: "Tony build Mark I",
        },
        href: "../Portfolio/Marvel/Iron-man-Mark-I.html",
        key: "project_Tony_build_Mark_I",
        date: "2022-05-29",
        relevance: 3,
        filter: "Iron man",
        img: "../img/Miniatures/mark1.jpg",
        alt: "Tony build Mark I",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Spiderman VS Electro//
        id: "moc-marvel-34",
        name: {
            fr: "Spiderman VS Electro",
            en: "Spiderman VS Electro",
        },
        href: "../Portfolio/Marvel/Spiderman-VS-Electro.html",
        key: "project_Spiderman_VS_Electro",
        date: "2021-12-30",
        relevance: 3,
        filter: "Spiderman : No way home",
        img: "../img/Miniatures/Spiderman VS Electro.jpg",
        alt: "Spiderman VS Electro",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//J. Jonah Jameson//
        id: "moc-marvel-35",
        name: {
            fr: "J. Jonah Jameson",
            en: "J. Jonah Jameson",
        },
        href: "../Portfolio/Marvel/J-Jonah-Jameson.html",
        key: "project_JJJ",
        date: "2021-12-19",
        relevance: 3,
        filter: "Spiderman : No way home",
        img: "../img/Miniatures/JJJ.jpg",
        alt: "J. Jonah Jameson",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Eternals opening scene//
        id: "moc-marvel-36",
        name: {
            fr: "Scène d'ouverture des Eternels",
            en: "Eternals opening scene",
        },
        href: "../Portfolio/Marvel/Eternals.html",
        key: "project_Eternals_opening_scene",
        date: "2021-11-27",
        relevance: 3,
        filter: "Eternals",
        img: "../img/Miniatures/eternals.jpg",
        alt: "Eternals opening scene",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Microscale Asgard//
        id: "moc-marvel-37",
        name: {
            fr: "Asgard miniature",
            en: "Microscale Asgard",
        },
        href: "../Portfolio/Marvel/Microscale-Asgard.html",
        key: "project_Microscale_Asgard",
        date: "2021-10-10",
        relevance: 3,
        filter: "Thor",
        img: "../img/Miniatures/asgard.jpg",
        alt: "Microscale Asgard",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Wandavision ep2//
        id: "moc-marvel-38",
        name: {
            fr: "Wandavision ep2",
            en: "Wandavision ep2",
        },
        href: "../Portfolio/Marvel/Wandavision-ep2.html",
        key: "project_Wandavision_ep2",
        date: "2021-10-07",
        relevance: 3,
        filter: "Wandavision",
        img: "../img/Miniatures/Wandavision ep2.jpg",
        alt: "Wandavision ep2",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Capture of Loki by TVA//
        id: "moc-marvel-39",
        name: {
            fr: "Capture de Loki par la TVA",
            en: "Capture of Loki by TVA",
        },
        href: "../Portfolio/Marvel/Loki-captured.html",
        key: "project_Capture_of_Loki_by_TVA",
        date: "2021-09-25",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/loki tva.jpg",
        alt: "Capture of Loki by TVA",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Loki in the void//
        id: "moc-marvel-40",
        name: {
            fr: "Loki dans le néant",
            en: "Loki in the void",
        },
        href: "../Portfolio/Marvel/Lokis-in-the-void.html",
        key: "project_Loki_in_the_void",
        date: "2021-09-18",
        relevance: 3,
        filter: "Loki",
        img: "../img/Miniatures/void.jpg",
        alt: "Loki in the void",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Iron man VS Ivan Vanko//
        id: "moc-marvel-41",
        name: {
            fr: "Iron man VS Ivan Vanko",
            en: "Iron man VS Ivan Vanko",
        },
        href: "../Portfolio/Marvel/Iron-man-in-Monaco.html",
        key: "project_Iron_man_VS_Ivan_Vanko",
        date: "2021-05-18",
        relevance: 3,
        filter: "Iron man 2",
        img: "../img/Miniatures/Iron man monaco.jpg",
        alt: "Iron man VS Ivan Vanko",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Killmonger death//
        id: "moc-marvel-42",
        name: {
            fr: "La mort de Killmonger",
            en: "Killmonger death",
        },
        href: "../Portfolio/Marvel/Killmonger-death-scene.html",
        key: "project_Killmonger_death_scene",
        date: "2021-05-16",
        relevance: 3,
        filter: "Black Panther",
        img: "../img/Miniatures/Killmonger death.jpg",
        alt: "Killmonger death",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Thor arrives in Wakanda//
        id: "moc-marvel-43",
        name: {
            fr: "Thor arrive au Wakanda",
            en: "Thor arrives in Wakanda",
        },
        href: "../Portfolio/Marvel/Thor-arrives-in-Wakanda.html",
        key: "project_Thor_arrives_in_Wakanda",
        date: "2021-05-14",
        relevance: 3,
        filter: "Avengers : Infinity War",
        img: "../img/Miniatures/thor arrives in wakanda.jpg",
        alt: "Thor arrives in Wakanda",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//arc reactor//
        id: "moc-marvel-44",
        name: {
            fr: "Réacteur Arc",
            en: "Arc reactor",
        },
        href: "../Portfolio/Marvel/Arc-Reactor.html",
        key: "project_arc_reactor",
        date: "2021-05-01",
        relevance: 3,
        filter: "Iron man",
        img: "../img/Miniatures/arc reactor.jpg",
        alt: "Arc reactor",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//TASM2 ending scene//
        id: "moc-marvel-45",
        name: {
            fr: "Scène finale de Amazing Spiderman",
            en: "TASM2 ending scene",
        },
        href: "../Portfolio/Marvel/TASM2.html",
        key: "project_TASM2_ending_scene",
        date: "2021-05-01",
        relevance: 3,
        filter: "The amazing Spiderman 2",
        img: "../img/Miniatures/TASM2.jpg",
        alt: "TASM2 ending scene",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Skrull transformation//
        id: "moc-marvel-46",
        name: {
            fr: "transformation des Skrull",
            en: "Skrull transformation",
        },
        href: "../Portfolio/Marvel/Skrull-transformation.Html",
        key: "project_Skrull_transformation",
        date: "2021-04-11",
        relevance: 3,
        filter: "Captain Marvel",
        img: "../img/Miniatures/skrull transformation.jpg",
        alt: "Skrull transformation",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Ancestral plane//
        id: "moc-marvel-47",
        name: {
            fr: "Plan ancestral",
            en: "Ancestral plane",
        },
        href: "../Portfolio/Marvel/Ancestral-Plane.html",
        key: "project_Ancestral_plane",
        date: "2021-04-10",
        relevance: 3,
        filter: "Black Panther",
        img: "../img/Miniatures/Ancestral plane.jpg",
        alt: "Ancestral plane",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },
    {//Arnim Zola//
        id: "moc-marvel-48",
        name: {
            fr: "Arnim Zola",
            en: "Arnim Zola",
        },
        href: "../Portfolio/Marvel/Arnim-Zola.html",
        key: "project_Arnim_Zola",
        date: "2021-04-07",
        relevance: 3,
        filter: "Captain America : The Winter soldier",
        img: "../img/Miniatures/arnim zola.jpg",
        alt: "Arnim Zola",
        type: "MOC",
        theme: "marvel",
        tag: "",
        favoris: false,
    },


    // Liste des MOC Jurassic Park //
    {//McDonald's Restaurant//
        id: "moc-jurassic-park-1",
        name: {
            fr: "Restaurant McDonald's",
            en: "McDonald's Restaurant",
        },
        href: "../Portfolio/Jurassic-Park/McDonald's.html",
        key: "",
        label: "McDonald's Restaurant",
        date: "2024-09-27",
        relevance: 3,
        filter: "Building",
        img: "../img/Miniatures/Mcdonalds.jpg",
        alt: "McDonald's Restaurant",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//QQS Restaurant//
        id: "moc-jurassic-park-2",
        name: {
            fr: "Restaurant QQS",
            en: "QQS Restaurant",
        },
        href: "../Portfolio/Jurassic-Park/QQS-restaurant.html",
        key: "",
        label: "QQS Restaurant",
        date: "2024-09-05",
        relevance: 3,
        filter: "Building",
        img: "../img/Miniatures/QQS restaurant.jpg",
        alt: "QQS Restaurant",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//Gift Shop//
        id: "moc-jurassic-park-3",
        name: {
            fr: "Magasin de souvenirs",
            en: "Gift Shop",
        },
        href: "../Portfolio/Jurassic-Park/Gift-shop.html",
        key: "",
        label: "Gift Shop",
        date: "2024-09-02",
        relevance: 3,
        filter: "Building",
        img: "../img/Miniatures/gift shop.jpg",
        alt: "Gift Shop",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//The Aviary//
        id: "moc-jurassic-park-4",
        name: {
            fr: "La volière",
            en: "The Aviary",
        },
        href: "../Portfolio/Jurassic-Park/Aviary.html",
        key: "project_Aviary",
        label: "The Aviary",
        date: "2024-08-30",
        relevance: 4,
        filter: "Landscape",
        img: "../img/Miniatures/aviary.jpg",
        alt: "The Aviary",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//The Mosasaurus (2)//
        id: "moc-jurassic-park-5",
        name: {
            fr: "Le Mosasaure (2)",
            en: "The Mosasaurus (2)",
        },
        href: "../Portfolio/Jurassic-Park/Mosasaurus.html",
        key: "project_The_Mosasaurus_2",
        label: "The Mosasaurus (2)",
        date: "2024-08-25",
        relevance: 5,
        filter: "Landscape",
        img: "../img/Miniatures/mosasaurus.jpg",
        alt: "The Mosasaurus (2)",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//Motorized Monorail//
        id: "moc-jurassic-park-6",
        name: {
            fr: "Monorail motorisé",
            en: "Motorized Monorail",
        },
        href: "../Portfolio/Jurassic-Park/Monorail.html",
        key: "project_Motorized_Monorail",
        label: "Motorized Monorail",
        date: "2022-05-15",
        relevance: 4,
        filter: "Landscape",
        img: "../img/Miniatures/monorail.jpg",
        alt: "Motorized Monorail",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//The Bowling//
        id: "moc-jurassic-park-7",
        name: {
            fr: "Le Bowling",
            en: "The Bowling",
        },
        href: "../Portfolio/Jurassic-Park/Bowling.html",
        key: "project_The_Bowling",
        label: "The Bowling",
        date: "2021-03-10",
        relevance: 3,
        filter: "Building",
        img: "../img/Miniatures/bowling.jpg",
        alt: "The Bowling",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//T-rex enclosure//
        id: "moc-jurassic-park-8",
        name: {
            fr: "L'enclos du T-rex",
            en: "T-rex enclosure",
        },
        href: "../Portfolio/Jurassic-Park/T-rex.html",
        key: "project_Trex_enclosure",
        label: "T-rex enclosure",
        date: "2021-03-07",
        relevance: 5,
        filter: "Landscape",
        img: "../img/Miniatures/t-rex.jpg",
        alt: "T-rex enclosure",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//Subway Restaurant//
        id: "moc-jurassic-park-9",
        name: {
            fr: "Restaurant Subway",
            en: "Subway Restaurant",
        },
        href: "../Portfolio/Jurassic-Park/Subway.html",
        key: "project_Subway_Restaurant",
        label: "Subway Restaurant",
        date: "2021-03-27",
        relevance: 3,
        filter: "Building",
        img: "../img/Miniatures/subway restaurant.png",
        alt: "Subway Restaurant",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//Coffee Chain Restaurant//
        id: "moc-jurassic-park-10",
        name: {
            fr: "Restaurant 'Coffee Chain'",
            en: "Coffee Chain Restaurant",
        },
        href: "../Portfolio/Jurassic-Park/Coffee-chain-restaurant.html",
        key: "project_The_Coffee_Chain_Restaurant",
        label: "Coffee Chain Restaurant",
        date: "2020-12-25",
        relevance: 1,
        filter: "Building",
        img: "../img/Miniatures/coffee chain 1.jpg",
        alt: "Coffee Chain Restaurant",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//Headquarter & Restaurant//
        id: "moc-jurassic-park-11",
        name: {
            fr: "Quartier général & Restaurant",
            en: "Headquarter & Restaurant",
        },
        href: "../Portfolio/Jurassic-Park/HQ-and-Restaurant.html",
        key: "project_Headquarter_Restaurant",
        label: "Headquarter & Restaurant",
        date: "2020-03-29",
        relevance: 2,
        filter: "Building",
        img: "../img/Miniatures/Restaurant.jpg",
        alt: "Headquarter & Restaurant",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//A laboratory in the jungle//
        id: "moc-jurassic-park-12",
        name: {
            fr: "Un laboratoire dans la jungle",
            en: "A laboratory in the jungle",
        },
        href: "../Portfolio/Jurassic-Park/Laboratory.html",
        key: "project_A_laboratory_in_the_jungle",
        label: "A laboratory in the jungle",
        date: "2020-01-04",
        relevance: 1,
        filter: "Landscape",
        img: "../img/Miniatures/Laboratory.jpg",
        alt: "A laboratory in the jungle",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },
    {//Archaeological excavations//
        id: "moc-jurassic-park-13",
        name: {
            fr: "Fouilles archéologiques",
            en: "Archaeological excavations",
        },
        href: "../Portfolio/Jurassic-Park/Excavations.html",
        key: "project_Archaeological_excavations",
        label: "Archaeological excavations",
        date: "2020-01-03",
        relevance: 2,
        filter: "Landscape",
        img: "../img/Miniatures/Fouilles.jpg",
        alt: "Archaeological excavations",
        type: "MOC",
        theme: "jurassic-park",
        tag: "",
        favoris: false,
    },


    //Liste des MOC Medieval//
    {//Building House//
        id: "moc-medieval-1",
        name: {
            fr: "Maison en construction",
            en: "Building House",
        },
        href: "../Portfolio/Medieval/Building House.html",
        key: "project_Building_House",
        label: "Building House",
        date: "2023-02-12",
        relevance: 3,
        filter: "Medieval",
        img: "../img/Miniatures/medieval.jpg",
        alt: "Building House",
        type: "MOC",
        theme: "medieval",
        tag: "",
        favoris: false,
    },

    //Liste des MOC City //
    {//Park Avenue//
        id: "moc-city-1",
        name: {
            fr: "Park Avenue, New York",
            en: "Park Avenue, New York",
        },
        href: "../Portfolio/City/Park-Avenue.html",
        key: "project_park_avenue",
        label: "Park Avenue",
        date: "2023-04-30",
        relevance: 3,
        filter: "City",
        img: "../img/Miniatures/Park Avenue.jpg",
        alt: "Park Avenue",
        type: "MOC",
        theme: "city",
        tag: "",
        favoris: false,
    },

    //Liste des MOC Wizarding World //
    {//Protego Diabolica//
        id: "moc-wizarding-world-1",
        name: {
            fr: "Protego Diabolica",
            en: "Protego Diabolica",
        },
        href: "../Portfolio/Wizarding-World/Protego-Diabolica.html",
        key: "project_Protego_Diabolica",
        label: "Protego Diabolica",
        date: "2023-04-30",
        relevance: 3,
        filter: "Fantastic Beasts: The Crimes of Grindelwald",
        img: "../img/Miniatures/protego diabolica.png",
        alt: "Protego Diabolica",
        type: "MOC",
        theme: "wizarding-world",
        tag: "",
        favoris: false,
    },
    {//Microscale Hogwarts//
        id: "moc-wizarding-world-2",
        name: {
            fr: "Poudlard Miniature",
            en: "Microscale Hogwarts",
        },
        href: "../Portfolio/Others/Microscale-Hogwarts.html",
        key: "project_Microscale_Hogwarts",
        label: "Microscale Hogwarts",
        date: "2020-10-26",
        relevance: 3,
        filter: "",
        img: "../img/Miniatures/hogwarts.jpg",
        alt: "Microscale Hogwarts",
        type: "MOC",
        theme: "wizarding-world",
        tag: "",
        favoris: false,
    },

    //Liste des MOC Autres//
    {//Paris 2024//
        id: "moc-others-1",
        name: {
            fr: "Piste athlétique Paris 2024",
            en: "Paris 2024 athletics track",
        },
        href: "../Portfolio/Others/Paris-2024.html",
        key: "project_Paris_2024_athletics_track",
        label: "Paris 2024 athletics track",
        date: "2024-08-10",
        relevance: 3,
        filter: "Others",
        img: "../img/Miniatures/paris 2024.png",
        alt: "Paris 2024 athletics track",
        type: "MOC",
        theme: "others",
        tag: "",
        favoris: false,
    },
    {//Percy Jackson and the Olympians//
        id: "moc-others-2",
        name: {
            fr: "Percy Jackson et les Olympiens",
            en: "Percy Jackson and the Olympians",
        },
        href: "../Portfolio/Others/Percy-Jackson-and-the-Olympians.html",
        key: "project_Percy_Jackson_and_the_Olympians",
        label: "Percy Jackson and the Olympians",
        date: "2024-10-25",
        relevance: 3,
        filter: "others",
        img: "../img/Miniatures/percy jackson.jpg",
        alt: "Percy Jackson and the Olympians",
        type: "MOC",
        theme: "Others",
        tag: "",
        favoris: false,
    },
    {//Alpine A523 & Ferrari SF23//
        id: "moc-others-3",
        name: {
            fr: "Alpine A523 & Ferrari SF23",
            en: "Alpine A523 & Ferrari SF23",
        },
        href: "../Portfolio/Others/F1.html",
        key: "project_Alpine_A523_Ferrari_SF23",
        label: "Alpine A523 & Ferrari SF23",
        date: "2023-08-12",
        relevance: 3,
        filter: "others",
        img: "../img/Miniatures/F1.png",
        alt: "Alpine A523 & Ferrari SF23",
        type: "MOC",
        theme: "Others",
        tag: "",
        favoris: false,
    },
    {//Explorer in the jungle//
        id: "moc-others-4",
        name: {
            fr: "Explorateur dans la jungle",
            en: "Explorer in the jungle",
        },
        href: "../Portfolio/Others/Explorer.html",
        key: "project_Explorer_in_the_jungle",
        label: "Explorer in the jungle",
        date: "2023-02-12",
        relevance: 3,
        filter: "others",
        img: "../img/Miniatures/explorer.jpg",
        alt: "Explorer in the jungle",
        type: "MOC",
        theme: "Others",
        tag: "",
        favoris: false,
    },
    {//Gladiators//
        id: "moc-others-5",
        name: {
            fr: "Gladiateurs",
            en: "Gladiators",
        },
        href: "../Portfolio/Others/Gladiators.html",
        key: "project_Gladiators",
        label: "Gladiators",
        date: "2021-10-30",
        relevance: 3,
        filter: "others",
        img: "../img/Miniatures/gladiator.jpg",
        alt: "Gladiators",
        type: "MOC",
        theme: "Others",
        tag: "",
        favoris: false,
    },
    {//A pirates fortress under attack//
        id: "moc-others-6",
        name: {
            fr: "Une forteresse pirate attaquée",
            en: "A pirates fortress under attack",
        },
        href: "../Portfolio/Others/Pirates-fortress.html",
        key: "project_A_pirates_fortress_under_attack",
        label: "A pirates fortress under attack",
        date: "2017-05-27",
        relevance: 1,
        filter: "others",
        img: "../img/Miniatures/pirate fortress.JPG",
        alt: "A pirates fortress under attack",
        type: "MOC",
        theme: "Others",
        tag: "",
        favoris: false,
    },
    {//A submerged greek temple//
        id: "moc-others-7",
        name: {
            fr: "Un temple grec submergé",
            en: "A submerged greek temple",
        },
        href: "../Portfolio/Others/Greek-temple.html",
        key: "project_A_submerged_greek_temple",
        label: "A submerged greek temple",
        date: "2017-04-11",
        relevance: 1,
        filter: "others",
        img: "../img/Miniatures/greek temple.jpg",
        alt: "A submerged greek temple",
        type: "MOC",
        theme: "Others",
        tag: "",
        favoris: false,
    },

    //Liste des figurines //
    {//Tony Stark//
        id: "minifig-1",
        name: "Tony Stark",
        film: "Avengers : Endgame",
        image: "img/Minifig/Stark-1-face.png",
        hoverImage: "img/Minifig/Stark-1-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb3107c01&idColor=11#T=S&C=11&O={%22color%22:11,%22iconly%22:0}'",
                image: "img/Portfolio/minifigs/973pb3107c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2893&idColor=88#T=S&C=88&O={%22color%22:88,%22iconly%22:0}'",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00pb0898&idColor=120&name=Dark%20Brown%20Hips%20and%20Legs%20with%20Molded%20Black%20Lower%20Legs%20/%20Boots%20and%20Printed%20Reddish%20Brown%20Belt%20and%20Strap%20with%20Silver%20Buckles,%20Boot%20Tongues%20with%20Laces,%20and%20Pouch%20on%20Right%20Side%20Pattern&category=%5BMinifigure,%20Legs,%20Decorated%5D#T=S&C=120&O={%22color%22:120,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00pb0898.png"
            },
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Howard Stark//
        name: "Howard Stark",
        film: "Avengers : Endgame",
        image: "img/Minifig/Howard-face.png",
        hoverImage: "img/Minifig/Howard-34.png", // image au survol
        parts: [
            {
                name: "Torso", link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head", link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs", link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Namora//
        name: "Namora",
        film: "Black Panther : Wakanda Forever",
        image: "img/Minifig/Namora-face.png",
        hoverImage: "img/Minifig/Namora-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Shuri//
        name: "Shuri",
        film: "Black Panther : Wakanda Forever",
        image: "img/Minifig/Shuri-1-face.png",
        hoverImage: "img/Minifig/Shuri-1-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Defender Strange//
        name: "Defender Strange",
        film: "Doctor Strange 2",
        image: "img/Minifig/Defender-strange-face.png",
        hoverImage: "img/Minifig/Defender-strange-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Heracles//
        name: "Heracles",
        film: "Thor : Love and Thunder",
        image: "img/Minifig/Hercules-face.png",
        hoverImage: "img/Minifig/Hercules-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Thor//
        name: "Thor",
        film: "Thor : Love and Thunder",
        image: "img/Minifig/Thor-1-face.png",
        hoverImage: "img/Minifig/Thor-1-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Baast//
        name: "Baast",
        film: "Thor : Love and Thunder",
        image: "img/Minifig/Baast-face.png",
        hoverImage: "img/Minifig/Baast-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Zeus//
        name: "Zeus",
        film: "Thor : Love and Thunder",
        image: "img/Minifig/Zeus-face.png",
        hoverImage: "img/Minifig/Zeus-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Love//
        name: "Love",
        film: "Thor : Love and Thunder",
        image: "img/Minifig/Love-face.png",
        hoverImage: "img/Minifig/Love-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Billy Maximoff//
        name: "Billy Maximoff",
        film: "WandaVision",
        image: "img/Minifig/Billy-Maximoff-face.png",
        hoverImage: "img/Minifig/Billy-Maximoff-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Ego//
        name: "Ego",
        film: "Guardians of the Galaxy",
        image: "img/Minifig/Ego-face.png",
        hoverImage: "img/Minifig/Ego-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Malekith//
        name: "Malekith",
        film: "Thor : The dark world",
        image: "img/Minifig/Malekith-face.png",
        hoverImage: "img/Minifig/Malekith-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs", link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//M'Baku//
        name: "M'Baku",
        film: "Black Panther",
        image: "img/Minifig/Mbaku-face.png",
        hoverImage: "img/Minifig/Mbaku-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Eddie Brock//
        name: "Eddie Brock",
        film: "Spiderman : No way home",
        image: "img/Minifig/Venom-face.png",
        hoverImage: "img/Minifig/Venom-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//The collector//
        name: "The Collector",
        film: "Guardians of the Galaxy",
        image: "img/Minifig/Collector-face.png",
        hoverImage: "img/Minifig/Collector-34.png", // image au survol
        parts: [
            {
                name: "Torso",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=973pb4482c01&idColor=1&name=White%20Torso%20Shirt,%20Light%20Nougat%20Neck,%20Buttons,%20Dark%20Bluish%20Gray%20and%20Tark%20Tan%20Floral%20Pattern%20/%20Light%20Nougat%20Arms%20with%20White%20Short%20Sleeves,%20Floral%20Pattern%20/%20Light%20Nougat%20Hands&category=%5BMinifigure,%20Torso%20Assembly,%20Decor.%5D#T=S&C=1&O={%22color%22:1,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/973pb4482c01.png"
            },
            {
                name: "Head",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626cpb2869&idColor=90#T=C&C=90",
                image: ""
            },
            {
                name: "Legs",
                link: "https://www.bricklink.com/v2/catalog/catalogitem.page?P=970c00#T=S&C=63&O={%22color%22:%2263%22,%22iconly%22:0}",
                image: "img/Portfolio/minifigs/970c00.png"
            }
        ],
        type: "minifig",
        theme: "",
        tag: "",
        favoris: false,
    },

    // Liste des instructions //
    {//Wooden table//
        id: "instruction-1",
        name: {
            fr: "Table en bois",
            en: "Wood table",
        },
        href: "img/instructions/Wooden table Instructions - Bricks Creations.pdf",
        key: "project_Agatha_on_the_Witches_road",
        date: "2024-10-09",
        relevance: 3,
        img: "img/Miniatures/Wood table.png",
        alt: "Wood table",
        type: "instruction",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Mcdonald's//
        id: "instruction-2",
        name: {
            fr: "Logo Mcdo",
            en: "Mcdo Logo",
        },
        href: "img/instructions/McDonald’s Logo Instructions - Bricks Creations.pdf",
        key: "project_Taweret_Boat",
        date: "2024-10-08",
        relevance: 3, img: "img/Miniatures/Mcdo Logo.png",
        alt: "Mcdo Logo",
        type: "instruction",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Subway//
        id: "instruction-3",
        name: {
            fr: "Logo Subway",
            en: "Subway Logo",
        },
        href: "img/instructions/Subway Logo Instructions - Bricks Creations.pdf",
        key: "project_Endgame_final_battle",
        date: "2024-08-09",
        relevance: 3,
        img: "img/Miniatures/Subway Logo.png",
        alt: "Subway Logo",
        type: "instruction",
        theme: "",
        tag: "",
        favoris: false,
    },
    { //Drone//
        id: "instruction-4",
        name: {
            fr: "Drone Far from home",
            en: "Drone Far from home",
        },
        href: "img/instructions/Drone Far From Home - Bricks Creations.pdf",
        key: "project_Thor_VS_Surtur",
        date: "2024-08-09",
        relevance: 3,
        img: "img/Miniatures/Drone far from home.png",
        alt: "Drone far from home",
        type: "instruction",
        theme: "",
        tag: "",
        favoris: false,
    },
    {//Wakanda Throne//
        id: "instruction-5",
        name: {
            fr: "Throne du Wakanda",
            en: "Wakanda throne",
        },
        href: "img/instructions/Wakanda Throne Instructions - Bricks Creations.pdf",
        key: "project_Steve_Rogers_transformation_scene",
        date: "2024-08-07",
        relevance: 3,
        img: "img/Miniatures/throne.png",
        alt: "Wakanda Throne",
        type: "instruction",
        theme: "",
        tag: "",
        favoris: false,
    },
    { //Innovation center//
        id: "instruction-6",
        name: {
            fr: "Innovation center",
            en: "Innovation center",
        },
        href: "img/instructions/Innovation center Instructions - Bricks Creations.pdf",
        date: "2024-08-04",
        relevance: 3,
        img: "img/Miniatures/Innovation center.png",
        alt: "Innovation center",
        type: "instruction",
        theme: "",
        tag: "",
        favoris: false,
    },
]

window.PROJECTS = project;